### ISSUE TITLE
Fetching all threads take so long

### ISSUE THREAD

**Issue by xupijack** [mathdroid/igdm-cli#2]
Fetching all threads take really long. is it possible to load faster?
btw, I want to work on this project nut i only know python.
Is there anyone can develop a python version of this?

**Comment by mathdroid** [comment]
Fetching all threads indeed will take longer depending on your number of `Thread`s. We can reduce the load time by using pagination by cursor. Our dependency, `instagram-private-api` supports that behavior. This is open for PR 👍 

@xupijack , it might be a good time to learn Node ;)

**Comment by mathdroid** [comment]
v0.2.1 fixed this. We call Inbox.get() at the beginning and added options to fetch older, fetch all, and refresh client.

@xupijack Hope it helps.
